### ISSUE TITLE
Bad behavoir

### ISSUE THREAD

**Issue by enningxie** [charlesXu86/Time_Convert#1]

**Comment by enningxie** [comment]
Occurred at "一点点".

**Comment by charlesXu86** [comment]
目前这类口语化的问题还有部分情况识别不了，还在优化中

**Comment by charlesXu86** [comment]
> Occurred at "一点点".

目前这类口语化的问题还有部分情况识别不了，还在优化中

**Comment by enningxie** [comment]
Thanks for replying 🙏, the tool is very useful 💗!
